backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    editor:
      preview: false
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Left Button Caption, name: leftcaption, widget: string}
          - {label: Left Button link, name: leftlink, widget: string}
          - {label: Right Button Caption, name: rightcaption, widget: string}
          - {label: Right Button link, name: rightlink, widget: string}
            
          
          - {label: Features Section, name: intro, widget: object, 
            fields: [{label: Heading, name: heading, widget: string}, 
            {label: Sub Heading, name: subheading, widget: string}, 

            {label: Features, name: blurbs, widget: list, 
            fields: [{label: Image, name: image, widget: image},
            {label: Title, name: title, widget: string}, 
            {label: Text, name: text, widget: text}]}]}

          - {label: Specialties Section, name: specialtiesintro, widget: object, 
            fields: [{label: Heading, name: heading, widget: string}, 
            {label: Description, name: description, widget: text},
            {label: Image, name: image, widget: image}, 

            {label: Specialties, name: specialtiesblurbs, widget: list, 
            fields: [{label: Title, name: title, widget: string}, 
            {label: Text, name: text, widget: text}]}]}

          - {label: Whyus Section, name: whyusintro, widget: object, 
            fields: [{label: Heading, name: heading, widget: string}, 
            {label: Sub Heading, name: subheading, widget: string}, 

            {label: Whyus Col, name: whyusblurbs, widget: list, 
            fields: [{label: Image, name: image, widget: image},
            {label: Title, name: title, widget: string}, 
            {label: Text, name: text, widget: text}]}]}

          - {label: Video Section, name: videointro, widget: object, 
            fields: [{label: Heading, name: heading, widget: string}, 
            {label: Sub Heading, name: subheading, widget: string}, 
            {label: Image, name: image, widget: image},
            {label: Youtube Video Id, name: videoid, widget: string}]}


          - {label: Highlighted Features One, name: featuresoneintro, widget: object, 
            fields: [{label: Heading, name: heading, widget: string}, 
            {label: Description, name: description, widget: text},
            {label: Image, name: image, widget: image},
            {label: Button Caption, name: caption, widget: string},
            {label: Button link, name: link, widget: string}]}

          - {label: Highlighted Features Two, name: featurestwointro, widget: object, 
            fields: [{label: Heading, name: heading, widget: string}, 
            {label: Description, name: description, widget: text},
            {label: Image, name: image, widget: image},
            {label: Button Caption, name: caption, widget: string},
            {label: Button link, name: link, widget: string}]}

          - {label: App Screenshot Previews, name: previewsintro, widget: object, 
            fields: [{label: Heading, name: heading, widget: string}, 
            {label: Sub Heading, name: subheading, widget: string}, 

            {label: Preview Images, name: previewblurbs, widget: list, 
            fields: [{label: Image, name: image, widget: image},
            {label: Image Title, name: title, widget: string},]}]}

          - {label: Testimonials Section, name: testimonialintro, widget: object, 
            fields: [{label: Heading, name: heading, widget: string}, 
            {label: Sub Heading, name: subheading, widget: string},  

            {label: Testimonial, name: testimonialblurbs, widget: list, 
            fields: [{label: Image, name: image, widget: image},
            {label: Name, name: title, widget: string},
            {label: Designation, name: designation, widget: string}, 
            {label: Text, name: text, widget: text}]}]}

          - {label: Team Section, name: teamintro, widget: object, 
            fields: [{label: Heading, name: heading, widget: string}, 
            {label: Sub Heading, name: subheading, widget: string}, 

            {label: Team, name: teamblurbs, widget: list, 
            fields: [{label: Image, name: image, widget: image},
            {label: Name, name: title, widget: string},
            {label: Designation, name: designation, widget: string}, 
            {label: Text, name: text, widget: text},
            {label: Facebook Profile Link, name: fb, widget: string},
            {label: Twitter Profile Link, name: tw, widget: string},
            {label: Google Profile Link, name: goo, widget: string},]}]}

          - {label: Download Software Section, name: downloadintro, widget: object, 
            fields: [{label: Heading, name: heading, widget: string}, 
            {label: Sub Heading, name: subheading, widget: string}, 
            {label: Text, name: text, widget: text},
            {label: Button Caption, name: caption, widget: string},
            {label: Button link, name: link, widget: string}]}

          
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: "Recommended Plan", name: "recommended", widget: "boolean"}, {label: Items, name: items, widget: list}, {label: Button Caption, name: caption, widget: string}, {label: Button link, name: link, widget: string}]}]}


      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
